# tasks file for roles/nignx

---
- name: Install Nginx
  yum: name=nginx state=present
  tags:
    - nginx
  notify:
    - restart nginx


# - name: insert firewalld rule for nginx
#   firewalld: port={{ nginx_port }}/tcp permanent=true state=enabled immediate=yes
#   ignore_errors: yes

- name: Nginx move ssl files
  template: src=ssl/buy.chuanboke.net/{{ item }} dest=/opt/ssl/
  with_items:
    - fullchain.pem
    - privkey.pem
  tags:
    - nginx
  notify:
    - restart nginx


- name: Nginx move sites.conf files
  template: src=sites.conf dest=/etc/nginx/conf.d/
  tags:
    - nginx
  notify:
    - restart nginx
