---

- name: Setup the Hualiang Web server
  hosts: web1
  # hosts: git.ct.boe.com.cn
  # hosts: boe-server
  become_user: root
  become: yes

  # pre_tasks:
  #   - name: Pre Task => Update Yum
  #     yum: name=* state=latest

  roles:
    - common
    - nginx
    - php71
    - supervisor
  # post_tasks:
  #   - name: post tasks
  #     yum: name=* state=latest

